// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tvcamoihpjujqppoghpw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR2Y2Ftb2locGp1anFwcG9naHB3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwNTg0NzUsImV4cCI6MjA2MTYzNDQ3NX0.nnaCJz8jgFPxlnEPW3dItDjANhKR2L3ZE2nFi4-yqAw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);